import { PERMISSION_GROUPS } from "./permissions";

// Shared between prisma/seed.ts (Paracon demo data) and lib/organisations.ts
// (provisioning a brand-new tenant from the Super Admin area) so both paths
// create the same permissions/roles/modules instead of two copies drifting.

export const PERMISSION_LABELS: Record<string, string> = {
  "tender.view": "View tenders",
  "tender.edit": "Edit tenders",
  "project.view": "View projects",
  "project.edit": "Edit projects",
  "program.edit": "Edit construction program",
  "labour.view": "View labour intelligence",
  "worker.edit": "Edit worker records",
  "forecast.view": "View labour forecast & capacity",
  "compliance.manage": "Manage compliance documents",
  "allocation.edit": "Edit resource allocation",
  "site.update": "Submit site daily updates",
  "dashboard.director": "View Director dashboard",
  "dashboard.pm": "View PM dashboard",
  "admin.users": "Manage users",
  "admin.roles": "Manage roles & permissions",
  "admin.ai": "Manage AI settings",
  "admin.billing": "Manage billing",
  "admin.modules": "Manage modules",
  "admin.branding": "Manage branding",
  "admin.audit": "View audit log",
  "admin.settings": "Manage settings registry",
  "ai.assistant.use": "Use AI assistant",
  "platform.superadmin": "Super admin (all tenants)",
};

export const ROLE_DEFINITIONS = [
  {
    slug: "director",
    name: "Director",
    permissions: [
      ...PERMISSION_GROUPS.admin,
      ...PERMISSION_GROUPS.tender,
      ...PERMISSION_GROUPS.project,
      ...PERMISSION_GROUPS.program,
      ...PERMISSION_GROUPS.labour,
      ...PERMISSION_GROUPS.forecast,
      ...PERMISSION_GROUPS.compliance,
      ...PERMISSION_GROUPS.allocation,
      ...PERMISSION_GROUPS.dashboard,
      ...PERMISSION_GROUPS.ai,
    ],
  },
  {
    slug: "project-manager",
    name: "Project Manager",
    permissions: [
      "project.view",
      "project.edit",
      "program.edit",
      "labour.view",
      "worker.edit",
      "forecast.view",
      "allocation.edit",
      "dashboard.pm",
      "ai.assistant.use",
    ],
  },
  {
    slug: "site-foreman",
    name: "Site Foreman",
    permissions: ["site.update"],
  },
  {
    slug: "estimator",
    name: "Estimator",
    permissions: ["tender.view", "tender.edit", "ai.assistant.use"],
  },
  {
    slug: "viewer",
    name: "Viewer",
    permissions: ["project.view", "tender.view", "forecast.view", "dashboard.pm"],
  },
] as const;

export const MODULES = [
  { slug: "tender", label: "Tender Pipeline", description: "Tender register and pipeline KPIs" },
  { slug: "projects", label: "Projects & Program", description: "Project register and construction program" },
  { slug: "labour", label: "Labour Intelligence", description: "Worker database and skills matrix" },
  { slug: "forecast", label: "Forecast & Capacity", description: "Labour demand/supply forecast engine" },
  { slug: "allocation", label: "Resource Allocation", description: "Worker allocation planner" },
  { slug: "site-updates", label: "Site Daily Updates", description: "Foreman mobile daily update flow" },
  { slug: "productivity", label: "Productivity & Estimating", description: "Productivity DB and estimating feedback loop" },
] as const;

export const CONFIG_DEFAULTS = [
  {
    key: "tender.statusList",
    group: "tender",
    type: "LIST" as const,
    label: "Tender statuses",
    description: "Status options available on a tender.",
    valueJson: ["In Progress", "Submitted", "Won", "Lost", "Withdrawn", "Post Tender"],
  },
  {
    key: "tender.winProbWeights",
    group: "tender",
    type: "WEIGHTS" as const,
    label: "Win probability weights",
    description: "Numeric weight applied per win-probability text value.",
    valueJson: { High: 0.8, Medium: 0.5, Low: 0.2 },
  },
  {
    key: "tender.statusWeights",
    group: "tender",
    type: "WEIGHTS" as const,
    label: "Status weights",
    description: "Numeric weight applied per tender status for weighted pipeline.",
    valueJson: {
      "In Progress": 0.3,
      Submitted: 0.5,
      "Post Tender": 0.2,
      Won: 1.0,
      Lost: 0.0,
      Withdrawn: 0.0,
    },
  },
  {
    key: "tender.valueBands",
    group: "tender",
    type: "BANDS" as const,
    label: "Tender value bands",
    description: "Bid-size bands used for pipeline intelligence.",
    valueJson: [
      { label: "<500k", max: 500_000 },
      { label: "500k–1m", max: 1_000_000 },
      { label: "1m–1.5m", max: 1_500_000 },
      { label: ">1.5m", max: null },
    ],
  },
  {
    key: "tender.outcomeList",
    group: "tender",
    type: "LIST" as const,
    label: "Tender outcome options",
    description: "Outcome options recorded once a tender is resolved, separate from its working status.",
    valueJson: ["Awaiting Result", "Won", "Lost", "No Bid", "Negotiating"],
  },
  {
    key: "client.statusList",
    group: "tender",
    type: "LIST" as const,
    label: "Client statuses",
    description: "Status options available on a client (head contractor) record.",
    valueJson: ["Pricing", "Pause"],
  },
  {
    key: "tender.bidDecisionList",
    group: "tender",
    type: "LIST" as const,
    label: "Bid decision options",
    description: "Go / no-go decision options recorded on a tender.",
    valueJson: ["Go", "No Go", "Service Client"],
  },
  {
    key: "tender.intentList",
    group: "tender",
    type: "LIST" as const,
    label: "Intent options",
    description: "Pursuit intent options recorded on a tender.",
    valueJson: ["Pursue", "Pass", "Passive"],
  },
  {
    key: "forecast.ragThresholds",
    group: "forecast",
    type: "WEIGHTS" as const,
    label: "Forecast RAG thresholds",
    description: "Coverage ratio thresholds for green/amber/red capacity status.",
    valueJson: { green: 1.0, amber: 0.85, red: 0.7 },
  },
  {
    key: "forecast.blockLengthDays",
    group: "forecast",
    type: "NUMBER" as const,
    label: "Forecast block length (days)",
    description: "Length of each demand/supply block in the forecast matrix (default 3 weeks).",
    valueJson: 21,
  },
  {
    key: "forecast.weeksOut",
    group: "forecast",
    type: "NUMBER" as const,
    label: "Forecast horizon (weeks)",
    description: "How many weeks ahead the forecast matrix and capacity headroom look.",
    valueJson: 12,
  },
  {
    key: "forecast.heatmapWeeks",
    group: "forecast",
    type: "NUMBER" as const,
    label: "Heatmap width (weeks)",
    description: "How many weeks wide the trade x week capacity heatmap is.",
    valueJson: 8,
  },
  {
    key: "project.statusList",
    group: "project",
    type: "LIST" as const,
    label: "Project statuses",
    description: "Health status options available on a project.",
    valueJson: ["On Track", "Attention", "Critical"],
  },
  {
    key: "activity.statusList",
    group: "project",
    type: "LIST" as const,
    label: "Program activity statuses",
    description: "Status options available on a construction program activity.",
    valueJson: ["On Track", "Watch", "At Risk", "Complete"],
  },
  {
    key: "milestone.typeList",
    group: "project",
    type: "LIST" as const,
    label: "Milestone types",
    description: "Milestone type options available when an activity is flagged critical.",
    valueJson: ["Fit-Out Start", "Services Rough-In", "Practical Completion", "Handover"],
  },
  {
    key: "trade.capabilityList",
    group: "labour",
    type: "LIST" as const,
    label: "Trade / capability list",
    description:
      "Worker trade and capability tags available across the app. Shared by Worker.capability and " +
      "ProgramActivity.trade so the Forecast & Capacity engine can match demand to supply directly.",
    valueJson: [
      "Site Foreman",
      "Lead Carpenter",
      "All-round Carpenter",
      "Carpenter",
      "Electrician",
      "Plumber",
      "Plasterer",
      "Painter",
      "Site Labourer",
      "Project Engineer",
    ],
  },
  {
    key: "worker.employmentTypeList",
    group: "labour",
    type: "LIST" as const,
    label: "Worker employment types",
    description: "Employment type options available on a worker record.",
    valueJson: ["Direct Employee", "Subcontractor", "Casual"],
  },
  {
    key: "worker.statusList",
    group: "labour",
    type: "LIST" as const,
    label: "Worker statuses",
    description: "Availability status options available on a worker record.",
    valueJson: ["Available", "Assigned", "On Leave"],
  },
  {
    key: "compliance.typeList",
    group: "labour",
    type: "LIST" as const,
    label: "Compliance document types",
    description: "Compliance document type options available on a worker.",
    valueJson: ["White Card", "Company Induction", "Uniform", "License", "Ticket"],
  },
  {
    key: "compliance.expiringThresholdDays",
    group: "labour",
    type: "NUMBER" as const,
    label: "Compliance expiring threshold (days)",
    description: "A compliance document is flagged Expiring once its expiry date is within this many days.",
    valueJson: 30,
  },
  {
    key: "branding.accentSwatches",
    group: "branding",
    type: "LIST" as const,
    label: "Allowed accent colours",
    description: "Brand-guardrail accent swatches an org can choose for its theme.",
    valueJson: ["#B08D57", "#9C7A4A", "#C49B63", "#8A6F3F", "#A6824F"],
  },
];
