import { PERMISSION_GROUPS } from "./permissions";

// Shared between prisma/seed.ts (Paracon demo data) and lib/organisations.ts
// (provisioning a brand-new tenant from the Super Admin area) so both paths
// create the same permissions/roles/modules instead of two copies drifting.

export const PERMISSION_LABELS: Record<string, string> = {
  "prospect.view": "View prospects",
  "prospect.edit": "Edit prospects & convert to tender",
  "tender.view": "View tenders",
  "tender.edit": "Edit tenders",
  "project.view": "View projects",
  "project.edit": "Edit projects",
  "program.edit": "Edit construction program",
  "labour.view": "View labour intelligence",
  "worker.edit": "Edit worker records",
  "forecast.view": "View labour forecast & capacity",
  "compliance.manage": "Manage compliance documents",
  "allocation.edit": "Edit resource allocation",
  "site.update": "Submit site daily updates",
  "scorecard.view": "View staff scorecards",
  "scorecard.assess": "Assess monthly staff scorecards",
  "doc.view": "View documents (stored & linked)",
  "doc.edit": "Upload, version, link & tag documents",
  "doc.generate": "Generate tender letters, variations & progress claims",
  "finance.view": "View project financials, POs, bills & claims",
  "finance.edit": "Record POs, deliveries & supplier bills; allocate unallocated bills",
  "finance.approve": "Approve/query/reject supplier bills and variations/claims",
  "import.run": "Run Import Centre importers",
  "dashboard.director": "View Director dashboard",
  "dashboard.pm": "View PM dashboard",
  "admin.users": "Manage users",
  "admin.roles": "Manage roles & permissions",
  "admin.ai": "Manage AI settings",
  "admin.billing": "Manage billing",
  "admin.modules": "Manage modules",
  "admin.branding": "Manage branding",
  "admin.audit": "View audit log",
  "admin.settings": "Manage settings registry",
  "ai.assistant.use": "Use AI assistant",
  "platform.superadmin": "Super admin (all tenants)",
};

export const ROLE_DEFINITIONS = [
  {
    slug: "director",
    name: "Director",
    permissions: [
      ...PERMISSION_GROUPS.admin,
      ...PERMISSION_GROUPS.prospect,
      ...PERMISSION_GROUPS.tender,
      ...PERMISSION_GROUPS.project,
      ...PERMISSION_GROUPS.program,
      ...PERMISSION_GROUPS.labour,
      ...PERMISSION_GROUPS.forecast,
      ...PERMISSION_GROUPS.compliance,
      ...PERMISSION_GROUPS.allocation,
      ...PERMISSION_GROUPS.dashboard,
      ...PERMISSION_GROUPS.ai,
      ...PERMISSION_GROUPS.document,
      ...PERMISSION_GROUPS.finance,
      ...PERMISSION_GROUPS.import,
      ...PERMISSION_GROUPS.scorecard,
    ],
  },
  {
    slug: "project-manager",
    name: "Project Manager",
    permissions: [
      "project.view",
      "project.edit",
      "program.edit",
      "labour.view",
      "worker.edit",
      "forecast.view",
      "allocation.edit",
      "dashboard.pm",
      "ai.assistant.use",
      "doc.view",
      "doc.edit",
      "doc.generate",
      "finance.view",
      "finance.edit",
      "finance.approve",
      "scorecard.view",
      "scorecard.assess",
    ],
  },
  {
    slug: "site-foreman",
    name: "Site Foreman",
    permissions: ["site.update", "doc.view", "doc.edit", "scorecard.view"],
  },
  {
    slug: "estimator",
    name: "Estimator",
    permissions: [
      "prospect.view",
      "prospect.edit",
      "tender.view",
      "tender.edit",
      "ai.assistant.use",
      "doc.view",
      "doc.edit",
      "doc.generate",
      "import.run",
      "scorecard.view",
    ],
  },
  {
    slug: "viewer",
    name: "Viewer",
    permissions: [
      "prospect.view",
      "project.view",
      "tender.view",
      "forecast.view",
      "doc.view",
      "finance.view",
      "scorecard.view",
    ],
  },
] as const;

export const MODULES = [
  { slug: "tender", label: "Tender Pipeline", description: "Tender register and pipeline KPIs" },
  { slug: "projects", label: "Projects & Program", description: "Project register and construction program" },
  { slug: "labour", label: "Labour Intelligence", description: "Worker database and skills matrix" },
  { slug: "forecast", label: "Forecast & Capacity", description: "Labour demand/supply forecast engine" },
  { slug: "allocation", label: "Resource Allocation", description: "Worker allocation planner" },
  { slug: "site-updates", label: "Site Daily Updates", description: "Foreman mobile daily update flow" },
  { slug: "productivity", label: "Productivity & Estimating", description: "Productivity DB and estimating feedback loop" },
  { slug: "finance", label: "Project Financials & Invoice Review", description: "POs, deliveries, supplier bill review and progress claim approval" },
] as const;

export const CONFIG_DEFAULTS = [
  {
    key: "prospect.stageList",
    group: "prospect",
    type: "LIST" as const,
    label: "Prospect stages",
    description: "Stage options available on a prospect, cold to warm.",
    valueJson: ["Cold", "Warm"],
  },
  {
    key: "supplier.kindList",
    group: "supplier",
    type: "LIST" as const,
    label: "Supplier kinds",
    description: "Category options for a supplier — supplier (materials/hire) or subcontractor (trade labour).",
    valueJson: ["Supplier", "Subcontractor"],
  },
  {
    key: "tender.statusList",
    group: "tender",
    type: "LIST" as const,
    label: "Tender statuses",
    description: "Status options available on a tender.",
    valueJson: ["In Progress", "Submitted", "Won", "Lost", "Withdrawn", "Post Tender"],
  },
  {
    key: "tender.winProbWeights",
    group: "tender",
    type: "WEIGHTS" as const,
    label: "Win probability weights",
    description: "Numeric weight applied per win-probability text value.",
    valueJson: { High: 0.8, Medium: 0.5, Low: 0.2 },
  },
  {
    key: "tender.statusWeights",
    group: "tender",
    type: "WEIGHTS" as const,
    label: "Status weights",
    description: "Numeric weight applied per tender status for weighted pipeline.",
    valueJson: {
      "In Progress": 0.3,
      Submitted: 0.5,
      "Post Tender": 0.2,
      Won: 1.0,
      Lost: 0.0,
      Withdrawn: 0.0,
    },
  },
  {
    key: "tender.valueBands",
    group: "tender",
    type: "BANDS" as const,
    label: "Tender value bands",
    description: "Bid-size bands used for pipeline intelligence.",
    valueJson: [
      { label: "<500k", max: 500_000 },
      { label: "500k–1m", max: 1_000_000 },
      { label: "1m–1.5m", max: 1_500_000 },
      { label: ">1.5m", max: null },
    ],
  },
  {
    key: "tender.outcomeList",
    group: "tender",
    type: "LIST" as const,
    label: "Tender outcome options",
    description: "Outcome options recorded once a tender is resolved, separate from its working status.",
    valueJson: ["Awaiting Result", "Won", "Lost", "No Bid", "Negotiating"],
  },
  {
    key: "client.statusList",
    group: "tender",
    type: "LIST" as const,
    label: "Client statuses",
    description: "Status options available on a client (head contractor) record.",
    valueJson: ["Pricing", "Pause"],
  },
  {
    key: "tender.bidDecisionList",
    group: "tender",
    type: "LIST" as const,
    label: "Bid decision options",
    description: "Go / no-go decision options recorded on a tender.",
    valueJson: ["Go", "No Go", "Service Client"],
  },
  {
    key: "tender.intentList",
    group: "tender",
    type: "LIST" as const,
    label: "Intent options",
    description: "Pursuit intent options recorded on a tender.",
    valueJson: ["Pursue", "Pass", "Passive"],
  },
  {
    key: "forecast.ragThresholds",
    group: "forecast",
    type: "WEIGHTS" as const,
    label: "Forecast RAG thresholds",
    description: "Coverage ratio thresholds for green/amber/red capacity status.",
    valueJson: { green: 1.0, amber: 0.85, red: 0.7 },
  },
  {
    key: "forecast.blockLengthDays",
    group: "forecast",
    type: "NUMBER" as const,
    label: "Forecast block length (days)",
    description: "Length of each demand/supply block in the forecast matrix (default 3 weeks).",
    valueJson: 21,
  },
  {
    key: "forecast.weeksOut",
    group: "forecast",
    type: "NUMBER" as const,
    label: "Forecast horizon (weeks)",
    description: "How many weeks ahead the forecast matrix and capacity headroom look.",
    valueJson: 12,
  },
  {
    key: "forecast.heatmapWeeks",
    group: "forecast",
    type: "NUMBER" as const,
    label: "Heatmap width (weeks)",
    description: "How many weeks wide the trade x week capacity heatmap is.",
    valueJson: 8,
  },
  {
    key: "project.statusList",
    group: "project",
    type: "LIST" as const,
    label: "Project statuses",
    description: "Health status options available on a project.",
    valueJson: ["On Track", "Attention", "Critical"],
  },
  {
    key: "activity.statusList",
    group: "project",
    type: "LIST" as const,
    label: "Program activity statuses",
    description: "Status options available on a construction program activity.",
    valueJson: ["On Track", "Watch", "At Risk", "Complete"],
  },
  {
    key: "milestone.typeList",
    group: "project",
    type: "LIST" as const,
    label: "Milestone types",
    description: "Milestone type options available when an activity is flagged critical.",
    valueJson: ["Fit-Out Start", "Services Rough-In", "Practical Completion", "Handover"],
  },
  {
    key: "trade.capabilityList",
    group: "labour",
    type: "LIST" as const,
    label: "Trade / capability list",
    description:
      "Worker trade and capability tags available across the app. Shared by Worker.capability and " +
      "ProgramActivity.trade so the Forecast & Capacity engine can match demand to supply directly.",
    valueJson: [
      "Site Foreman",
      "Lead Carpenter",
      "All-round Carpenter",
      "Carpenter",
      "Electrician",
      "Plumber",
      "Plasterer",
      "Painter",
      "Site Labourer",
      "Project Engineer",
    ],
  },
  {
    key: "worker.employmentTypeList",
    group: "labour",
    type: "LIST" as const,
    label: "Worker employment types",
    description: "Employment type options available on a worker record.",
    valueJson: ["Direct Employee", "Subcontractor", "Casual"],
  },
  {
    key: "schedule.delayReasonList",
    group: "schedule",
    type: "LIST" as const,
    label: "Delay reasons",
    description:
      "Reason tags required when a Gantt task is pushed to a later date — captured on the DelayRecord " +
      "for EOT/Notice-of-Delays reporting.",
    valueJson: ["Material Delay", "Weather", "Sub No Show", "QA Check Failed", "Admin OOO", "Equipment fault"],
  },
  {
    key: "worker.statusList",
    group: "labour",
    type: "LIST" as const,
    label: "Worker statuses",
    description: "Availability status options available on a worker record.",
    valueJson: ["Available", "Assigned", "On Leave"],
  },
  {
    key: "compliance.typeList",
    group: "labour",
    type: "LIST" as const,
    label: "Compliance document types",
    description: "Compliance document type options available on a worker.",
    valueJson: ["White Card", "Company Induction", "Uniform", "License", "Ticket"],
  },
  {
    key: "compliance.expiringThresholdDays",
    group: "labour",
    type: "NUMBER" as const,
    label: "Compliance expiring threshold (days)",
    description: "A compliance document is flagged Expiring once its expiry date is within this many days.",
    valueJson: 30,
  },
  {
    key: "productivity.standardHoursPerDay",
    group: "productivity",
    type: "NUMBER" as const,
    label: "Standard hours per day",
    description: "Hours per crew-day used to convert a program activity's planned headcount into planned labour hours.",
    valueJson: 8,
  },
  {
    key: "scorecard.metrics",
    group: "productivity",
    type: "METRICS" as const,
    label: "Staff Scorecard metrics",
    description:
      "The 3-5 weighted metrics scored on the monthly Staff Scorecard. AUTO metrics are computed from daily " +
      "updates/allocations; MANUAL metrics are entered by the assessing Director/PM.",
    valueJson: [
      { key: "quality", label: "Quality", weight: 0.25, scaleMax: 5, source: "MANUAL" },
      { key: "reliability", label: "Reliability", weight: 0.25, scaleMax: 5, source: "AUTO" },
      { key: "productivity", label: "Productivity", weight: 0.25, scaleMax: 5, source: "AUTO" },
      { key: "safety", label: "Safety", weight: 0.25, scaleMax: 5, source: "MANUAL" },
    ],
  },
  {
    key: "branding.accentSwatches",
    group: "branding",
    type: "LIST" as const,
    label: "Allowed accent colours",
    description: "Brand-guardrail accent swatches an org can choose for its theme.",
    valueJson: ["#B08D57", "#9C7A4A", "#C49B63", "#8A6F3F", "#A6824F"],
  },
  {
    key: "document.projectCategoryList",
    group: "document",
    type: "LIST" as const,
    label: "Project document categories",
    description:
      "Section labels the Documents panel scaffolds for every project, mirroring the master PROJECT folder template " +
      "(_MASTER PROJECT TEMPLATE) so nothing is hunted for in nested folders.",
    valueJson: [
      "Submission, Contract & Claims",
      "Quotes & Purchase Orders",
      "Documentation",
      "Handover Manual",
      "Site File",
      "General",
    ],
  },
  {
    key: "document.tenderCategoryList",
    group: "document",
    type: "LIST" as const,
    label: "Tender document categories",
    description:
      "Section labels the Documents panel scaffolds for every tender, mirroring the master TENDER folder template " +
      "(_ MASTER TEMPLATE (duplicate only)).",
    valueJson: ["Documentation", "Measure", "Submission", "Supplier Quotes", "General"],
  },
  {
    key: "document.linkedKindList",
    group: "document",
    type: "LIST" as const,
    label: "Linked document kinds",
    description: "Kind options for a Google-Drive-linked document (large CAD/drawing sets that stay in Drive).",
    valueJson: ["Drawing Set", "CAD File", "Architectural Specification", "Photo Archive", "Other"],
  },
  {
    key: "document.generatedDocumentProjectCategory",
    group: "document",
    type: "TEXT" as const,
    label: "Generated document category (project)",
    description:
      "Which entry in document.projectCategoryList a generated Variation/Progress Claim files under. Must match " +
      "an entry in that list exactly, or it won't group under any category in the Documents panel.",
    valueJson: "Submission, Contract & Claims",
  },
  {
    key: "document.generatedDocumentTenderCategory",
    group: "document",
    type: "TEXT" as const,
    label: "Generated document category (tender)",
    description:
      "Which entry in document.tenderCategoryList a generated Tender Letter files under. Must match an entry in " +
      "that list exactly, or it won't group under any category in the Documents panel.",
    valueJson: "Submission",
  },
  {
    key: "document.generatedStatusList",
    group: "document",
    type: "LIST" as const,
    label: "Generated document statuses",
    description:
      "Status options for a generated Tender Letter / Variation / Progress Claim — e.g. a Variation can be marked " +
      "Withdrawn instead of that state only living in a folder name, as it did in the source Drive structure.",
    valueJson: ["Issued", "Withdrawn", "Superseded"],
  },
  {
    key: "document.defaultTradePackageList",
    group: "document",
    type: "LIST" as const,
    label: "Default trade packages",
    description:
      "Starter trade-package list for a new tender/project (Tender Letter pricing rows, Progress Claim contract-work " +
      "rows). Per-project/tender editable — the source templates show this varies job to job, not a fixed enum.",
    valueJson: ["Partitions", "Doors", "Ceiling"],
  },
  {
    key: "document.gstRatePct",
    group: "document",
    type: "NUMBER" as const,
    label: "GST rate (%)",
    description: "Applied to every generated Tender Letter, Variation and Progress Claim total.",
    valueJson: 10,
  },
  {
    key: "document.tenderLetter.marginDefaultPct",
    group: "document",
    type: "NUMBER" as const,
    label: "Tender Letter default margin (%)",
    description: "Default margin applied to cost to derive the client sell price on a new Tender Letter (per-letter editable).",
    valueJson: 6,
  },
  {
    key: "document.tenderLetter.marginFormula",
    group: "document",
    type: "TEXT" as const,
    label: "Tender Letter margin formula",
    description:
      'How margin is applied to cost: "MARGIN_ON_SELL" (sell = cost / (1 - margin%), margin as a % of the sell ' +
      'price) or "MARKUP_ON_COST" (sell = cost * (1 + margin%), margin as a % markup on cost).',
    valueJson: "MARGIN_ON_SELL",
  },
  {
    key: "document.tenderLetter.roundingBasis",
    group: "document",
    type: "TEXT" as const,
    label: "Tender Letter rounding basis",
    description:
      'Which total the "round up" rule applies to before GST/total are derived from it: "EX_GST" (the ex-GST ' +
      'subtotal) or "INC_GST" (the GST-inclusive total).',
    valueJson: "EX_GST",
  },
  {
    key: "document.tenderLetter.roundUpToNearest",
    group: "document",
    type: "NUMBER" as const,
    label: "Tender Letter round up to nearest ($)",
    description: 'The tender price is rounded UP to the next multiple of this amount (Paracon\'s SOP is $10,000).',
    valueJson: 10000,
  },
  {
    key: "document.tenderLetter.numberPrefix",
    group: "document",
    type: "TEXT" as const,
    label: "Tender Letter number prefix",
    description: 'Prefix for an auto-generated Tender Letter number (e.g. "TL-" produces "TL-01"). Leave blank for a bare number.',
    valueJson: "TL-",
  },
  {
    key: "document.tenderLetter.numberPadding",
    group: "document",
    type: "NUMBER" as const,
    label: "Tender Letter number padding (digits)",
    description: 'Zero-pads the Tender Letter sequence number to this many digits (2 produces "TL-01"). 0 disables padding.',
    valueJson: 2,
  },
  {
    key: "document.variation.numberPrefix",
    group: "document",
    type: "TEXT" as const,
    label: "Variation number prefix",
    description: 'Prefix for an auto-generated Variation number (Paracon\'s convention is "VQ-", per-project sequential).',
    valueJson: "VQ-",
  },
  {
    key: "document.variation.numberPadding",
    group: "document",
    type: "NUMBER" as const,
    label: "Variation number padding (digits)",
    description: 'Zero-pads the Variation sequence number to this many digits (2 produces "VQ-01"). 0 disables padding.',
    valueJson: 2,
  },
  {
    key: "document.variation.validityDays",
    group: "document",
    type: "NUMBER" as const,
    label: "Variation validity (days)",
    description: 'Number of days a Variation Quotation stays valid from its issue date, stated in its Terms clause.',
    valueJson: 7,
  },
  {
    key: "document.progressClaim.numberPrefix",
    group: "document",
    type: "TEXT" as const,
    label: "Progress Claim number prefix",
    description: 'Prefix for an auto-generated Progress Claim number (e.g. "Claim #" produces "Claim #3").',
    valueJson: "Claim #",
  },
  {
    key: "document.progressClaim.numberPadding",
    group: "document",
    type: "NUMBER" as const,
    label: "Progress Claim number padding (digits)",
    description: "Zero-pads the Progress Claim sequence number to this many digits. 0 disables padding.",
    valueJson: 0,
  },
  {
    key: "document.swms.numberPrefix",
    group: "document",
    type: "TEXT" as const,
    label: "SWMS number prefix",
    description: 'Prefix for an auto-generated Safe Work Method Statement number (e.g. "SWMS-" produces "SWMS-01"), per-project sequential.',
    valueJson: "SWMS-",
  },
  {
    key: "document.swms.numberPadding",
    group: "document",
    type: "NUMBER" as const,
    label: "SWMS number padding (digits)",
    description: 'Zero-pads the SWMS sequence number to this many digits (2 produces "SWMS-01"). 0 disables padding.',
    valueJson: 2,
  },
  {
    key: "finance.po.numberPrefix",
    group: "finance",
    type: "TEXT" as const,
    label: "Purchase Order number prefix",
    description: 'Prefix for an auto-generated PO number (e.g. "PO-" produces "PO-01"), per-project sequential.',
    valueJson: "PO-",
  },
  {
    key: "finance.po.numberPadding",
    group: "finance",
    type: "NUMBER" as const,
    label: "Purchase Order number padding (digits)",
    description: 'Zero-pads the PO sequence number to this many digits (2 produces "PO-01"). 0 disables padding.',
    valueJson: 2,
  },
  {
    key: "finance.po.statusList",
    group: "finance",
    type: "LIST" as const,
    label: "Purchase Order statuses",
    description: "Status options available on a purchase order.",
    valueJson: ["Draft", "Ordered", "Partially delivered", "Delivered", "Cancelled"],
  },
  {
    key: "finance.delivery.statusList",
    group: "finance",
    type: "LIST" as const,
    label: "Delivery statuses",
    description: "Status options available on a delivery record.",
    valueJson: ["Pending", "Delivered", "Delayed", "Partial"],
  },
  {
    key: "finance.bill.statusList",
    group: "finance",
    type: "LIST" as const,
    label: "Supplier bill statuses",
    description:
      "Status pipeline for an incoming supplier bill: Received (auto-pulled or manually added) -> Under review " +
      "(PM checklist in progress) -> Approved/Queried/Rejected -> Sent to EzzyBills (handed onward, exactly as " +
      "today) -> Paid -> Reconciled.",
    valueJson: ["Received", "Under review", "Approved", "Queried", "Rejected", "Sent to EzzyBills", "Paid", "Reconciled"],
  },
  {
    key: "finance.bill.allocationStatusList",
    group: "finance",
    type: "LIST" as const,
    label: "Supplier bill allocation statuses",
    description: "Whether an incoming bill has been matched to a project yet — drives the Unallocated tray.",
    valueJson: ["Unallocated", "Allocated"],
  },
  {
    key: "finance.variation.statusList",
    group: "finance",
    type: "LIST" as const,
    label: "Variation register statuses",
    description: "Commercial decision status for a Variation, separate from the underlying document's own status.",
    valueJson: ["Submitted", "Approved", "Outstanding", "Rejected"],
  },
  {
    key: "finance.progressClaim.statusList",
    group: "finance",
    type: "LIST" as const,
    label: "Progress Claim review statuses",
    description:
      "Internal review/approve/issue pipeline for a generated Progress Claim, ahead of being marked issued to the client.",
    valueJson: ["Draft", "Under review", "Approved", "Issued", "Certified", "Paid"],
  },
  {
    key: "finance.retention.ratePct",
    group: "finance",
    type: "NUMBER" as const,
    label: "Retention rate per claim (%)",
    description: "Percentage withheld from each progress claim as retention, until the cap is reached.",
    valueJson: 10,
  },
  {
    key: "finance.retention.capPct",
    group: "finance",
    type: "NUMBER" as const,
    label: "Retention cap (% of contract value)",
    description: "Cumulative retention held never exceeds this percentage of the (variation-adjusted) contract value.",
    valueJson: 5,
  },
  {
    key: "finance.retention.pcReleaseFractionPct",
    group: "finance",
    type: "NUMBER" as const,
    label: "Retention released at Practical Completion (% of held)",
    description:
      "Fraction of the retention held that releases at Practical Completion (default 50% of the 5% cap, i.e. 2.5% " +
      "of contract value released, 2.5% remaining for the final release).",
    valueJson: 50,
  },
  {
    key: "finance.retentionReleaseTypeList",
    group: "finance",
    type: "LIST" as const,
    label: "Retention release types",
    description: "Type options when recording a retention release against a project.",
    valueJson: ["PracticalCompletion", "Final"],
  },
  {
    key: "finance.reconcile.tolerancePct",
    group: "finance",
    type: "NUMBER" as const,
    label: "PO/bill reconcile tolerance (%)",
    description: "Total billed against a PO is flagged over budget once it exceeds the PO value by more than this percentage.",
    valueJson: 5,
  },
  {
    key: "finance.po.openStatusesForBillMatch",
    group: "finance",
    type: "LIST" as const,
    label: "PO statuses considered \"open\" for bill auto-matching",
    description:
      "When the mailbox watcher auto-allocates an incoming bill, it only links it to a PO in one of these statuses " +
      "(an unambiguous single match is required).",
    valueJson: ["Ordered", "Partially delivered"],
  },
  {
    key: "site.issueSeverityList",
    group: "site",
    type: "LIST" as const,
    label: "Site issue severities",
    description: "Severity chips available when a foreman raises an issue from the mobile daily update.",
    valueJson: ["Low", "Medium", "High"],
  },
  {
    key: "site.issueStatusList",
    group: "site",
    type: "LIST" as const,
    label: "Site issue statuses",
    description: "Status pipeline for an issue raised from a foreman daily update.",
    valueJson: ["Open", "In Progress", "Resolved"],
  },
  {
    key: "site.photoTagList",
    group: "site",
    type: "LIST" as const,
    label: "Site photo tags",
    description: "Tag options for a photo attached to a foreman daily update.",
    valueJson: ["Progress", "Delivery", "Issue", "Other"],
  },
  {
    key: "dashboard.health.attentionMilestoneWindowDays",
    group: "dashboard",
    type: "NUMBER" as const,
    label: "Project health — attention window (days)",
    description:
      "A project's nearest upcoming critical milestone inside this many days (and not already overdue) flags the project Attention on the Director/PM dashboards.",
    valueJson: 10,
  },
  {
    key: "dashboard.health.criticalIssueSeverities",
    group: "dashboard",
    type: "LIST" as const,
    label: "Project health — critical issue severities",
    description:
      "An open site issue at one of these severities (site.issueSeverityList values) flags the project Critical rather than Attention.",
    valueJson: ["High"],
  },
  {
    key: "dashboard.health.shortageWatchWeeks",
    group: "dashboard",
    type: "NUMBER" as const,
    label: "Project health — labour shortage watch window (weeks)",
    description:
      "A negative labour gap (demand over allocated) for a project inside this many weeks flags it Attention; a shortage in the current week flags it Critical.",
    valueJson: 2,
  },
  {
    key: "scorecard.gauge.goodThreshold",
    group: "scorecard",
    type: "NUMBER" as const,
    label: "Scorecard gauge — good threshold",
    description: "A staff scorecard's overall score (0-100) at or above this value renders the gauge in the RAG-green band.",
    valueJson: 80,
  },
  {
    key: "scorecard.gauge.warningThreshold",
    group: "scorecard",
    type: "NUMBER" as const,
    label: "Scorecard gauge — warning threshold",
    description:
      "A staff scorecard's overall score at or above this value (but below the good threshold) renders the gauge in the RAG-amber band; below it renders RAG-red.",
    valueJson: 60,
  },

  // ─── Simplified dashboard ────────────────────────────────────────────────────

  {
    key: "dashboard.simple.revenueTargetAud",
    group: "dashboard",
    type: "NUMBER" as const,
    label: "Revenue target (AUD)",
    description:
      "The annual revenue target the 'Revenue won' ring measures against on the simplified dashboard. Revenue won is the winning bid value of every tender marked Won.",
    valueJson: 5_000_000,
  },
  {
    key: "dashboard.simple.kpiGoodThreshold",
    group: "dashboard",
    type: "NUMBER" as const,
    label: "Simplified dashboard — good threshold (%)",
    description:
      "A KPI ring or bar at or above this percentage renders RAG-green. Applies to every percentage KPI on the simplified dashboard.",
    valueJson: 80,
  },
  {
    key: "dashboard.simple.kpiWarningThreshold",
    group: "dashboard",
    type: "NUMBER" as const,
    label: "Simplified dashboard — warning threshold (%)",
    description:
      "A KPI at or above this percentage (but below the good threshold) renders RAG-amber; below it renders RAG-red.",
    valueJson: 50,
  },
  {
    key: "dashboard.checklist.items",
    group: "dashboard",
    type: "CHECKLIST" as const,
    label: "KPI checklist items",
    description:
      "The daily and weekly checks shown on the simplified dashboard. Each user ticks their own copy; a daily tick clears overnight and a weekly tick clears when the ISO week turns over.",
    valueJson: [
      { key: "review-site-updates", label: "Review yesterday's site updates", cadence: "DAILY" },
      { key: "check-deliveries", label: "Check today's deliveries", cadence: "DAILY" },
      { key: "approve-variations", label: "Approve outstanding variations", cadence: "DAILY" },
      { key: "labour-forecast", label: "Review the labour forecast", cadence: "WEEKLY" },
      { key: "pipeline-review", label: "Review the tender pipeline", cadence: "WEEKLY" },
      { key: "compliance-expiry", label: "Check expiring compliance", cadence: "WEEKLY" },
    ],
  },

  // ─── Automation ──────────────────────────────────────────────────────────────

  {
    key: "automation.tenderAwardedOutcomes",
    group: "automation",
    type: "LIST" as const,
    label: "Tender outcomes that trigger project auto-create",
    description:
      "When a tender's outcome changes to one of these values, a Project is automatically created " +
      "from the tender's details, seeded with the Gantt template below, and the forecast is rewarmed. " +
      "Must match values in tender.outcomeList exactly.",
    valueJson: ["Won"],
  },
  {
    key: "automation.ganttTemplate",
    group: "automation",
    type: "LIST" as const,
    label: "Gantt template for auto-created projects",
    description:
      "Default program activities seeded when a project is auto-created from a Won tender. " +
      "Each entry: { name, trade, durationDays, orderIndex, isMilestone?, milestoneType? }. " +
      "Activities are chained sequentially from the project start date. " +
      "Editable per org without a code deploy (config-not-code).",
    valueJson: [
      { name: "Mobilisation",        trade: "Site Foreman",       durationDays: 5,  orderIndex: 0 },
      { name: "Demolition",          trade: "Site Labourer",      durationDays: 10, orderIndex: 1 },
      { name: "Services Rough-in",   trade: "Electrician",        durationDays: 14, orderIndex: 2 },
      { name: "Partitions",          trade: "All-round Carpenter", durationDays: 21, orderIndex: 3 },
      { name: "Ceilings",            trade: "All-round Carpenter", durationDays: 14, orderIndex: 4 },
      { name: "Doors & Hardware",    trade: "Carpenter",          durationDays: 10, orderIndex: 5 },
      { name: "Finishes & Painting", trade: "Painter",            durationDays: 10, orderIndex: 6 },
      { name: "Practical Completion",trade: "Site Foreman",       durationDays: 3,  orderIndex: 7, isMilestone: true, milestoneType: "Practical Completion" },
    ],
  },
  {
    key: "automation.projectCodePrefix",
    group: "automation",
    type: "TEXT" as const,
    label: "Auto-project code prefix",
    description:
      'Prefix for project codes generated by the tender-awarded automation (e.g. "P-" produces "P-001"). ' +
      "Set to an empty string for a bare number.",
    valueJson: "P-",
  },
  {
    key: "automation.projectCodePadding",
    group: "automation",
    type: "NUMBER" as const,
    label: "Auto-project code zero-padding (digits)",
    description:
      "Zero-pads the auto-project sequence number to this many digits (3 produces \"P-001\"). 0 disables padding.",
    valueJson: 3,
  },
  {
    key: "automation.billAutoHandoff",
    group: "automation",
    type: "TEXT" as const,
    label: "Auto-advance approved bills to Xero handoff",
    description:
      "When \"true\", the bill-approved automation automatically advances a bill from Approved to " +
      "\"Sent to EzzyBills\" so the accounts team's existing EzzyBills workflow picks it up without " +
      "a manual click. Set to \"false\" to require a manual advancement (the button still works either way).",
    valueJson: "true",
  },
];
